services:
  - type: web
    name: hospital-management
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: dpg-d0me5ce3jp1c7389cij0-a  # Без .internal!
      - key: DB_USER
        value: courceworkdb_user
      - key: DB_PASSWORD
        value: seychDMjHy556UPx7qWdjgVPUusN7ZKF
      - key: DB_NAME
        value: courceworkdb
      - key: DB_PORT
        value: 5432
      - key: JWT_SECRET
        generateValue: true
      - key: DB_SSL_MODE  # Добавляем явное указание SSL
        value: require